### ISSUE TITLE
How to run all doctests? Do we need a test runner?

### ISSUE THREAD

**Issue by justvanrossum** [robofab-developers/fontPens#11]
I think it's fine if `fontPens` uses doctest exclusively, but I'd like to know what the easiest way is to run everything. There are a bunch of them failing at the moment.

I could write a test runner script, but I'm afraid wasting time. @anthrotype, what's your advise?

**Comment by anthrotype** [comment]
pytest is already set up to discover and run the embedded doctests.

just do `pytest`, or if you don't have it already or don't want to install, just do `python setup.py test` (pytest will be bootstrapped automatically in the local directory's .eggs/)

**Comment by justvanrossum** [comment]
Thanks!

**Comment by anthrotype** [comment]
I see some of them are failing because fontParts is not installed. If it's required, then it should be listed in the install_requires (and packaged and uploaded to pypi, like fontPens itself).

if it's only required by the doctests, then we can add fontParts to tests_require keyword in setup.py (provided fontParts is available from PyPI).

Or for the time being we can tell pytest to ignore those ImportErrors raised from the doctests, with the `--doctest-ignore-import-errors` option. This can be added in the pytest section of the setup.cfg file (under `addopts` subsection).

**Comment by anthrotype** [comment]
also fontMath and defcon seems to be required for the doctests

**Comment by justvanrossum** [comment]
Those fontParts imports are rather crucial to do some decent testing, so I don't think it's a good idea to ignore those import errors.

**Comment by justvanrossum** [comment]
So yes, fontParts should be listed in test_require, and yes, ideally fontParts should be in PyPI.

**Comment by justvanrossum** [comment]
Also, some minimal Travis setup like fontParts has would be great for fontPens.
